/*
 * File: app/model/EquipaggiamentoModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.model.EquipaggiamentoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'codice',
        fields: [
            {
                name: 'codice',
                type: 'string'
            },
            {
                name: 'descrizione',
                type: 'string'
            },
            {
                name: 'equipPrezzo',
                type: 'string'
            },
            {
                name: 'cluster_codice',
                type: 'string'
            },
            {
                name: 'clusterUrlImg',
                type: 'string'
            },
            {
                name: 'gruppoDesc',
                type: 'string'
            },
            {
                name: 'infoFlag',
                type: 'string'
            },
            {
                name: 'stato',
                type: 'string'
            },
            {
                name: 'abbinamentoFlag',
                type: 'string'
            },
            {
                name: 'order',
                type: 'int'
            }
        ]
    }
});