/*
 * File: app/model/DettaglioVeicoloNuovoModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.model.DettaglioVeicoloNuovoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    config: {
        idProperty: 'codice',
        fields: [
            {
                name: 'codice',
                type: 'string'
            },
            {
                name: 'marca_codice',
                type: 'string'
            },
            {
                name: 'marca_descrizione',
                type: 'string'
            },
            {
                name: 'modello_codice',
                type: 'string'
            },
            {
                name: 'modello_descrizione',
                type: 'string'
            },
            {
                name: 'allestimento_codice',
                type: 'string'
            },
            {
                name: 'allestimento_descrizione',
                type: 'string'
            },
            {
                name: 'alimentazione_codice',
                type: 'string'
            },
            {
                name: 'alimentazione_descrizione',
                type: 'string'
            },
            {
                name: 'carrozzeria_codice',
                type: 'string'
            },
            {
                name: 'carrozzeria_descrizione',
                type: 'string'
            },
            {
                name: 'veicoloBasePrezzo',
                type: 'string'
            },
            {
                name: 'equipaggiamentiPrezzo',
                type: 'string'
            },
            {
                name: 'totalePrezzo',
                type: 'string'
            },
            {
                name: 'urlImg',
                type: 'string'
            }
        ],
        proxy: {
            type: 'rest',
            url: '/nuovo/dettaglioVeicolo',
            appendId: false,
            reader: {
                type: 'json',
                rootProperty: 'data'
            },
            writer: {
                type: 'json',
                allowSingle: false
            }
        }
    }
});