/*
 * File: app/view/HomeView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.HomeView', {
    extend: 'Ext.Container',
    alias: 'widget.HomeView',

    requires: [
        'Ext.Img',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.Container',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        itemId: 'homeView',
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'image',
                height: 200,
                width: 200
            },
            {
                xtype: 'label',
                itemId: 'welcomeHomeLabel',
                tpl: [
                    'Benvenuto {nomeUtente} {cognomeUtente}'
                ]
            },
            {
                xtype: 'label',
                hidden: true,
                itemId: 'messageHomeLabel'
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'ricercaUsatoHomeButton',
                        iconCls: 'action',
                        text: 'Ritiro'
                    },
                    {
                        xtype: 'spacer',
                        itemId: 'homeButtonsSpacer1',
                        width: 50
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'ricercaNuovoHomeButton',
                        iconCls: 'action',
                        text: 'Configurazione'
                    },
                    {
                        xtype: 'spacer',
                        itemId: 'homeButtonsSpacer2',
                        width: 50
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'ricercaStockHomeButton',
                        iconCls: 'action',
                        text: 'Stock'
                    }
                ]
            }
        ]
    }

});