/*
 * File: app/view/StockView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.StockView', {
    extend: 'Ext.Container',
    alias: 'widget.StockView',

    requires: [
        'Infocar.view.TopBar',
        'Ext.form.Panel',
        'Ext.Spacer',
        'Ext.field.Toggle',
        'Ext.field.Hidden',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.field.Select',
        'Ext.Button',
        'Ext.Img',
        'Ext.carousel.Carousel',
        'Ext.tab.Panel',
        'Ext.tab.Bar',
        'Ext.dataview.List'
    ],

    config: {
        itemId: 'stockView',
        layout: 'vbox',
        items: [
            {
                xtype: 'TopBar'
            },
            {
                xtype: 'container',
                flex: 1,
                itemId: 'bodyStockContainer',
                layout: {
                    type: 'card',
                    animation: 'slide'
                },
                items: [
                    {
                        xtype: 'container',
                        Titolo: 'Stock - Ricerca stock',
                        itemId: 'ricercaStockContainer',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                cls: 'ricercaStockFormCls',
                                itemId: 'ricercaStockForm',
                                layout: 'vbox',
                                scrollable: null,
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 3,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                itemId: 'descrizioneRicercaStockField',
                                                width: '60%',
                                                label: 'Targa o Descrizione',
                                                labelWidth: 200,
                                                name: 'descrizione'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 35
                                            },
                                            {
                                                xtype: 'togglefield',
                                                cls: 'stockUsatoRicercaStockToggleCls',
                                                itemId: 'stockUsatoRicercaStockToggle',
                                                label: 'Usato',
                                                labelWidth: '45%'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                itemId: 'stockUsatoRicercaStockHiddenField',
                                                name: 'stockUsatoFlag'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: 'stockUsatoRicercaStockLabelCls',
                                                html: 'Nuovo'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 3,
                                        itemId: 'mycontainer40',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'sliderfield',
                                                flex: 1,
                                                itemId: 'prezzoMinMaxRicercaStockSlider',
                                                component: {
                                                    allowThumbsOverlapping: true
                                                },
                                                label: 'Prezzo',
                                                labelCls: 'prezzoMinMaxRicercaStockSliderLabCls',
                                                labelWidth: 80,
                                                increment: 1000
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                itemId: 'prezzoMinRicercaStockHiddenField',
                                                name: 'minPrezzo'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                itemId: 'prezzoMaxRicercaStockHiddenField',
                                                name: 'maxPrezzo'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 30
                                            },
                                            {
                                                xtype: 'sliderfield',
                                                flex: 1,
                                                itemId: 'kmMinMaxRicercaStockSlider',
                                                component: {
                                                    allowThumbsOverlapping: true
                                                },
                                                label: 'KM',
                                                labelCls: 'kmMinMaxRicercaStockSliderLabCls',
                                                labelWidth: 60,
                                                increment: 1000
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                itemId: 'kmMinRicercaStockHiddenField',
                                                name: 'minKm'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                itemId: 'kmMaxRicercaStockHiddenField',
                                                name: 'maxKm'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 2,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'spacer',
                                                width: 80
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        flex: 1,
                                                        cls: 'prezzoMinRicercaStockLabelCls',
                                                        itemId: 'prezzoMinRicercaStockLabel',
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            '{prezzo:this.fmtCurrency} &euro;',
                                                            {
                                                                fmtCurrency: function(currValue) {
                                                                    return Infocar.app.formatCurrency2(currValue);
                                                                }
                                                            }
                                                        )
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 1,
                                                        cls: 'prezzoMaxRicercaStockLabelCls',
                                                        itemId: 'prezzoMaxRicercaStockLabel',
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            '{prezzo:this.fmtCurrency} &euro;',
                                                            {
                                                                fmtCurrency: function(currValue) {
                                                                    return Infocar.app.formatCurrency2(currValue);
                                                                }
                                                            }
                                                        )
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 90
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        flex: 1,
                                                        cls: 'kmMinRicercaStockLabelCls',
                                                        itemId: 'kmMinRicercaStockLabel',
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            '{km:this.fmtInt} Km',
                                                            {
                                                                fmtInt: function(intValue) {
                                                                    return Infocar.app.formatInt(intValue);
                                                                }
                                                            }
                                                        )
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 1,
                                                        cls: 'kmMaxRicercaStockLabelCls',
                                                        itemId: 'kmMaxRicercaStockLabel',
                                                        style: '{text-align:right;}',
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            '{km:this.fmtInt} Km',
                                                            {
                                                                fmtInt: function(intValue) {
                                                                    return Infocar.app.formatInt(intValue);
                                                                }
                                                            }
                                                        )
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 3,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                flex: 1,
                                                label: 'Alimentazione',
                                                labelWidth: 200,
                                                name: 'alimentazione_codice',
                                                autoSelect: false,
                                                displayField: 'descrizione',
                                                store: 'AlimentazioneRicercaStockStore',
                                                valueField: 'codice'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 30
                                            },
                                            {
                                                xtype: 'selectfield',
                                                flex: 1,
                                                label: 'Carrozzeria',
                                                labelWidth: 200,
                                                name: 'carrozzeria_codice',
                                                autoSelect: false,
                                                displayField: 'descrizione',
                                                store: 'CarrozzeriaRicercaStockStore',
                                                valueField: 'codice'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 3,
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'end'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                baseCls: 'cercaRicStockButtonCls',
                                                itemId: 'cercaRicStockButton',
                                                text: 'Cerca'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'ricercaStockRisultatoContainer',
                                layout: {
                                    type: 'card',
                                    animation: 'slide'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'veicoloRicStockRisultatoContainer',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                cls: 'veicoloRicStockNumRisultatiContainerCls',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'center',
                                                    pack: 'center'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'component',
                                                        baseCls: 'leftVeicoloRicStockNumRisultatiSpacerCls'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 1,
                                                        baseCls: 'veicoloRicStockNumRisultatiLabelCls',
                                                        itemId: 'veicoloRicStockNumRisultatiLabel'
                                                    },
                                                    {
                                                        xtype: 'selectfield',
                                                        cls: 'ordinamentoRicStockComboBoxCls',
                                                        itemId: 'ordinamentoRicStockComboBox',
                                                        label: 'Ordina per:',
                                                        labelWidth: '40%',
                                                        name: 'ordinamento_codice',
                                                        autoSelect: false,
                                                        displayField: 'descrizione',
                                                        store: 'OrdinamentoRicercaStockStore',
                                                        valueField: 'codice'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                cls: 'veicoloRicStockRisultatoDataViewCls',
                                                itemId: 'veicoloRicStockRisultatoDataView',
                                                itemTpl: [
                                                    '<table class="veicoloRicStockRisultatoDataViewTableCls">',
                                                    '  <tr>',
                                                    '    <td class="logoVeicoloRicStockRisultatoDataViewTdCls"><img src="{urlImg}" class="logoVeicoloRicStockRisultatoDataViewImgCls"></td>',
                                                    '    <td class="descrizioneVeicoloRicStockRisultatoDataViewTdCls">',
                                                    '        <div class="descrizione1VeicoloRicStockRisultatoDataViewDivCls">{descrizione1}</div>',
                                                    '        <div class="descrizione2VeicoloRicStockRisultatoDataViewDivCls">{descrizione2}</div>',
                                                    '        <div class="descrizione3VeicoloRicStockRisultatoDataViewDivCls">{descrizione3}</div>',
                                                    '        <div class="descrizione4VeicoloRicStockRisultatoDataViewDivCls">{descrizione4}</div>',
                                                    '    </td>',
                                                    '    <td class="frecciaVeicoloRicStockRisultatoDataViewTdCls"><img src="resources/images/freccia_dx.jpg" class="frecciaVeicoloRicStockRisultatoDataViewImgCls"></td>',
                                                    '  </tr>',
                                                    '</table>',
                                                    ''
                                                ],
                                                pressedDelay: 10,
                                                store: 'VeicoloStockStore',
                                                useComponents: false
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        Titolo: 'Stock - Dettaglio veicolo',
                        itemId: 'infoVeicoloStockContainer',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                hidden: true,
                                itemId: 'testataInfoVeicoloStockContainerLandscape',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'image',
                                        height: 50,
                                        itemId: 'infoVeicoloStockMiniImg',
                                        width: 50
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'descInfoVeicoloStockLabel',
                                        tpl: [
                                            '{veicoloStock_descrizione}'
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'rightInfoVeicoloStockContainerCls',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        cls: 'testataInfoVeicoloStockContainerPortraitCls',
                                        itemId: 'testataInfoVeicoloStockContainerPortrait',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                height: 50,
                                                width: 50,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        centered: true,
                                                        itemId: 'infoVeicoloStockMiniImg',
                                                        imageCls: 'infoVeicoloStockMiniImgCls',
                                                        mode: 'image'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                cls: 'descTestataInfoVeicoloStockContainerPortraitCls',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'center'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        cls: 'descInfoVeicoloStockLabelPortraitCls',
                                                        itemId: 'descInfoVeicoloStockLabel',
                                                        tpl: [
                                                            '{veicoloStock_descrizione}'
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        itemId: 'corpoInfoVeicoloStockContainer',
                                        layout: {
                                            type: 'card',
                                            animation: 'slide'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                cls: 'generaleInfoVeicoloStockContainerCls',
                                                itemId: 'generaleInfoVeicoloStockContainer',
                                                layout: 'vbox',
                                                scrollable: 'vertical',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        cls: 'testoImgInfoVeicoloStockContainerCls',
                                                        width: '100%',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'carousel',
                                                                itemId: 'infoVeicoloStockCarousel',
                                                                width: 313
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                flex: 1,
                                                                cls: 'testoinfoVeicoloStockContainerCls',
                                                                itemId: 'testoinfoVeicoloStockContainer',
                                                                items: [
                                                                    {
                                                                        xtype: 'label',
                                                                        cls: 'testoInfoVeicoloStockLabelCls',
                                                                        itemId: 'testoInfoVeicoloStockLabel',
                                                                        tpl: Ext.create('Ext.XTemplate', 
                                                                            '<div class="labelPrezzoVendTestoInfoVeicoloStockDivCls">Prezzo di vendita</div>',
                                                                            '<div class="valorePrezzoVendTestoInfoVeicoloStockDivCls">{venditaPrezzo:this.fmtCurrency} &euro;</div>',
                                                                            '<br>',
                                                                            '<div class="prezziTestoInfoVeicoloStockDivCls">',
                                                                            'Codice infocar: {codiceInfocar}<br>',
                                                                            'Codice casa: {codiceCasa}<br>',
                                                                            'Codice QUD: {codiceQUD}<br>',
                                                                            'Omologazioni: {omologazioni}<br>',
                                                                            '</div>',
                                                                            {
                                                                                fmtCurrency: function(currValue) {
                                                                                    return Infocar.app.formatCurrency(currValue);
                                                                                }
                                                                            }
                                                                        ),
                                                                        width: '100%'
                                                                    },
                                                                    {
                                                                        xtype: 'container',
                                                                        cls: 'prezziInfoVeicoloStockOverlayContainerCls',
                                                                        height: 58,
                                                                        itemId: 'prezziInfoVeicoloStockOverlayContainer',
                                                                        top: 0,
                                                                        width: '100%',
                                                                        layout: 'hbox',
                                                                        scrollable: false,
                                                                        items: [
                                                                            {
                                                                                xtype: 'button',
                                                                                baseCls: 'frecciaPrezziInfoVeicoloStockButtonCls',
                                                                                height: 58,
                                                                                itemId: 'frecciaPrezziInfoVeicoloStockButton',
                                                                                width: 57
                                                                            },
                                                                            {
                                                                                xtype: 'label',
                                                                                flex: 1,
                                                                                cls: 'testoPrezziInfoVeicoloStockLabelCls',
                                                                                itemId: 'testoPrezziInfoVeicoloStockLabel',
                                                                                tpl: [
                                                                                    '<div style="width: 100%; text-align: right">',
                                                                                    '    <p>Prezzo alternativo: {alternativoPrezzo} &euro;</p>',
                                                                                    '    <p>Prezzo minimo di vendita: {minimoPrezzo} &euro;</p>',
                                                                                    '</div>'
                                                                                ]
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        cls: 'sintesiEquipInfoVeicoloStockContainerCls',
                                                        height: 102,
                                                        itemId: 'sintesiEquipInfoVeicoloStockContainer',
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'center'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                flex: 1,
                                                                cls: 'sintesiEquipInfoVeicoloStockLabelCls',
                                                                itemId: 'sintesiEquipInfoVeicoloStockLabel',
                                                                tpl: [
                                                                    '<div class="titoloSintesiEquipInfoVeicoloStockDivCls">Equipaggiamenti</div>',
                                                                    '<div class="descSintesiEquipInfoVeicoloStockDivCls">',
                                                                    'Questo allestimento comprende {numEquip} equipaggiamenti',
                                                                    '</div>',
                                                                    ''
                                                                ],
                                                                width: '80%'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                baseCls: 'equipInfoVeicoloStockButtonCls',
                                                                height: 37,
                                                                hidden: false,
                                                                itemId: 'equipInfoVeicoloStockButton',
                                                                width: 37
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: 'titoloSchedaInfoVeicoloStockLabelCls',
                                                        html: 'Scheda veicolo'
                                                    },
                                                    {
                                                        xtype: 'tabpanel',
                                                        height: 'auto',
                                                        itemId: 'schedaInfoVeicoloStockTabPanelCls',
                                                        items: [
                                                            {
                                                                xtype: 'container',
                                                                title: 'INFORMAZIONI AGGIUNTIVE',
                                                                cls: 'informAggiuntiveSchedaInfoVeicoloStockTabCls',
                                                                height: 'auto',
                                                                layout: 'fit',
                                                                scrollable: false,
                                                                items: [
                                                                    {
                                                                        xtype: 'label',
                                                                        height: 'auto',
                                                                        itemId: 'informAggiuntiveSchedaInfoVeicoloStockLabel',
                                                                        tpl: [
                                                                            'aertar tawrt farwgt arwegt arwg tewr gtea rg ewrag erw<br/><br/><br/><br/><br/>sdfwrgthyj{infoAggiuntiveSchedaVeicolo}'
                                                                        ]
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                title: 'STATO D\'USO',
                                                                cls: 'statoUsoSchedaInfoVeicoloStockTabCls',
                                                                height: 'auto',
                                                                layout: 'fit',
                                                                scrollable: false,
                                                                items: [
                                                                    {
                                                                        xtype: 'label',
                                                                        height: 'auto',
                                                                        itemId: 'statoUsoSchedaInfoVeicoloStockLabel',
                                                                        tpl: [
                                                                            '{statoUsoSchedaVeicolo}'
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ],
                                                        tabBar: {
                                                            cls: 'schedaInfoVeicoloStockTabBarCls',
                                                            docked: 'top',
                                                            ui: 'untitled-ui-3'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        cls: 'sintesiDatiTecniciInfoVeicoloStockContainerCls',
                                                        height: 115,
                                                        itemId: 'sintesiDatiTecniciInfoVeicoloStockContainer',
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'center'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                flex: 1,
                                                                cls: 'sintesiDatiTecniciInfoVeicoloStockLabelCls',
                                                                itemId: 'sintesiDatiTecniciInfoVeicoloStockLabel',
                                                                tpl: [
                                                                    '<div class="titoloSintesiDatiTecniciInfoVeicoloStockDivCls">Dati tecnici</div>',
                                                                    '<div class="descSintesiDatiTecniciInfoVeicoloStockDivCls">',
                                                                    'Alimentazione: <span class="infocar-bold">{alimentazione_descrizione}</span>&nbsp;&nbsp;',
                                                                    'Cilindrata cm<sup>3</sup>: <span class="infocar-bold">{cilindrata}</span>&nbsp;&nbsp;',
                                                                    'Potenza kW/CV: <span class="infocar-bold">{potenza}</span><br>',
                                                                    'Carrozzeria: <span class="infocar-bold">{carrozzeria_descrizione}</span>&nbsp;&nbsp;',
                                                                    'Normativa: <span class="infocar-bold">{normativa}</span>',
                                                                    '</div>'
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                baseCls: 'datiTecniciInfoVeicoloStockButtonCls',
                                                                height: 37,
                                                                itemId: 'datiTecniciInfoVeicoloStockButton',
                                                                width: 37
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        itemId: 'sintesiSituazioneStockVeicoloStockContainer',
                                                        layout: 'vbox',
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                cls: 'sintesiSituazioneStockVeicoloStockLabelCls',
                                                                html: 'Situazione in stock'
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                cls: 'datiPrevisiviDatiStockInfoVeicoloStockContainerCls',
                                                                layout: 'hbox',
                                                                items: [
                                                                    {
                                                                        xtype: 'label',
                                                                        cls: 'sintesiDatiPrevisiviInfoVeicoloStockLabelCls',
                                                                        itemId: 'sintesiDatiPrevisiviInfoVeicoloStockLabel',
                                                                        tpl: Ext.create('Ext.XTemplate', 
                                                                            '<table class="sintesiDatiPrevisiviInfoVeicoloStockTableCls">',
                                                                            '    <tr class="headerSintesiDatiPrevisiviInfoVeicoloStockTrCls">',
                                                                            '        <td></td>',
                                                                            '        <td>Valore previsivo a 3 mesi</td>',
                                                                            '        <td>Valore previsivo a 6 mesi</td>',
                                                                            '    </tr>',
                                                                            '    <tr class="venditaSintesiDatiPrevisiviInfoVeicoloStockTrCls">',
                                                                            '        <td>Vendita</td>',
                                                                            '        <td>{venditaValoreMesi3:this.fmtInt}</td>',
                                                                            '        <td>{venditaValoreMesi6:this.fmtInt}</td>',
                                                                            '    </tr>',
                                                                            '    <tr class="rititoSintesiDatiPrevisiviInfoVeicoloStockTrCls">',
                                                                            '        <td>Ritiro</td>',
                                                                            '        <td>{ritiroValoreMesi3:this.fmtInt}</td>',
                                                                            '        <td>{ritiroValoreMesi6:this.fmtInt}</td>',
                                                                            '    </tr>',
                                                                            '</table>',
                                                                            {
                                                                                fmtInt: function(intValue) {
                                                                                    return Infocar.app.formatInt(intValue);
                                                                                }
                                                                            }
                                                                        ),
                                                                        width: '50%'
                                                                    },
                                                                    {
                                                                        xtype: 'label',
                                                                        cls: 'sintesiDatiStockInfoVeicoloStockLabelCls',
                                                                        itemId: 'sintesiDatiStockInfoVeicoloStockLabel',
                                                                        tpl: Ext.create('Ext.XTemplate', 
                                                                            '<table class="sintesiDatiStockInfoVeicoloStockTableCls">',
                                                                            '    <tr class="headerSintesiDatiStockInfoVeicoloStockTrCls">',
                                                                            '        <td>In stock</td>',
                                                                            '        <td>Fisico</td>',
                                                                            '        <td>Virtuale</td>',
                                                                            '        <td>Giacenza media</td>',
                                                                            '        <td>Giacenza modello</td>',
                                                                            '    </tr>',
                                                                            '    <tr class="allestimentoSintesiDatiStockInfoVeicoloStockTrCls">',
                                                                            '        <td>Allestimento</td>',
                                                                            '        <td>{allestimentoFisicoStock:this.fmtInt}</td>',
                                                                            '        <td>{allestimentoVirtualeStock:this.fmtInt}</td>',
                                                                            '        <td>{allestimentoGiacenzaStock:this.fmtInt}</td>',
                                                                            '        <td>{allestimentoGiacMediaStock:this.fmtInt}&nbsp;<img src="{allestimentoGiacenzaStockUrlImg}" class="sintesiDatiStockInfoVeicoloStockImgCls"></td>',
                                                                            '    </tr>',
                                                                            '    <tr class="modelloSintesiDatiStockInfoVeicoloStockTrCls">',
                                                                            '        <td>Modello</td>',
                                                                            '        <td>{modelloFisicoStock:this.fmtInt}</td>',
                                                                            '        <td>{modelloVirtualeStock:this.fmtInt}</td>',
                                                                            '        <td>{modelloGiacenzaStock:this.fmtInt}</td>',
                                                                            '        <td>{modelloGiacMediaStock:this.fmtInt}&nbsp;<img src="{modelloGiacenzaStockUrlImg}" class="sintesiDatiStockInfoVeicoloStockImgCls"></td>',
                                                                            '    </tr>',
                                                                            '</table>',
                                                                            '',
                                                                            {
                                                                                fmtInt: function(intValue) {
                                                                                    return Infocar.app.formatInt(intValue);
                                                                                }
                                                                            }
                                                                        ),
                                                                        width: '50%'
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                cls: 'datiTecniciInfoVeicoloStockContainerCls',
                                                itemId: 'datiTecniciInfoVeicoloStockContainer',
                                                layout: 'vbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        cls: 'titoloDatiTecniciInfoVeicoloStockLabelCls',
                                                        html: 'Dati tecnici'
                                                    },
                                                    {
                                                        xtype: 'list',
                                                        flex: 1,
                                                        cls: 'datiTecniciInfoVeicoloStockListViewCls',
                                                        disableSelection: true,
                                                        itemCls: 'datiTecniciInfoVeicoloStockListViewItemCls',
                                                        itemTpl: [
                                                            '<table class="datiTecniciInfoVeicoloStockTableCls">',
                                                            '  <tr>',
                                                            '    <td class="attributoDatiTecniciInfoVeicoloStockTdCls">{nomeAttributo}:</td>',
                                                            '    <td class="valoreDatiTecniciInfoVeicoloStockTdCls">{valoreAttributo}</td>',
                                                            '  </tr>',
                                                            '</table>',
                                                            ''
                                                        ],
                                                        store: 'DatiTecniciInfoVeicoloStockStore',
                                                        grouped: true,
                                                        itemHeight: 34
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'equipInfoVeicoloStockContainer',
                                                layout: 'vbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        cls: 'titoloEquipSerieInfoVeicoloStockLabelCls',
                                                        html: 'Equipaggiamenti di serie'
                                                    },
                                                    {
                                                        xtype: 'dataview',
                                                        flex: 1,
                                                        cls: 'equipSerieInfoVeicoloStockDataviewCls',
                                                        itemTpl: Ext.create('Ext.XTemplate', 
                                                            '<div class="descEquipSerieInfoVeicoloStockDataviewItemDivCls"> > {descrizione}</div>',
                                                            {
                                                                disableFormats: true
                                                            }
                                                        ),
                                                        store: 'EquipSerieInfoVeicoloStockStore'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: 'titoloEquipMontatiInfoVeicoloStockLabelCls',
                                                        html: 'Equipaggiamenti montati'
                                                    },
                                                    {
                                                        xtype: 'dataview',
                                                        flex: 1,
                                                        cls: 'equipMontatiInfoVeicoloStockDataviewCls',
                                                        itemTpl: Ext.create('Ext.XTemplate', 
                                                            '<div class="descEquipMontatiInfoVeicoloNuovoDataviewItemDivCls"> > {descrizione}</div>',
                                                            {
                                                                disableFormats: true
                                                            }
                                                        ),
                                                        store: 'EquipMontatiInfoVeicoloStockStore'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                height: 60,
                                hidden: false,
                                ui: 'infocar-toolbar',
                                layout: {
                                    type: 'hbox',
                                    align: 'start'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        baseCls: 'indietroInfoVeicoloStockButtonCls',
                                        itemId: 'indietroInfoVeicoloStockButton',
                                        text: 'INDIETRO'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        itemId: 'stampaInfoVeicoloStockButton',
                                        text: 'Stampa'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});