/*
 * File: app/view/TopBar.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.TopBar', {
    extend: 'Ext.Container',
    alias: 'widget.TopBar',

    requires: [
        'Ext.Container',
        'Ext.Button',
        'Ext.Img',
        'Ext.Label',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'topBarCls',
        height: 135,
        itemId: 'topBar',
        layout: {
            type: 'vbox',
            align: 'start'
        },
        items: [
            {
                xtype: 'container',
                cls: 'upTopBarContainerCls',
                height: 79,
                minHeight: 45,
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        baseCls: 'showMainMenuLeftButtonCls',
                        height: 28,
                        itemId: 'showMainMenuLeftButton',
                        width: 34
                    },
                    {
                        xtype: 'image',
                        cls: 'logoTopBarImgCls',
                        height: 41,
                        width: 164,
                        src: 'resources/images/5-ipad_infocar_03.png'
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        cls: 'userNameTopBarLabelCls',
                        itemId: 'userNameTopBarLabel',
                        tpl: [
                            '<img src="resources/images/10-ipad_infocar_done_09.png" class="imgUserNameTopBarLabel">{nomeUtente} {cognomeUtente}'
                        ]
                    },
                    {
                        xtype: 'button',
                        baseCls: 'esciTopBarButtonCls',
                        height: 38,
                        itemId: 'esciTopBarButton',
                        width: 37
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'downTopBarContainerCls',
                height: 56,
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        cls: 'titoloSezioneTopBarLabelCls',
                        itemId: 'titoloSezioneTopBarLabel',
                        width: '100%'
                    }
                ]
            }
        ]
    }

});