/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.controller.MainController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Infocar.view.MainView'
    ],

    config: {
        control: {
            "button#stampaButton": {
                tap: 'onStampaButtonTap'
            },
            "container#bodyContainer": {
                activeitemchange: 'onContainerActiveItemChange'
            },
            "button#esciTopBarButton": {
                tap: 'onEsciTopBarButtonTap'
            }
        }
    },

    onStampaButtonTap: function(button, e, eOpts) {
        window.print();
    },

    onContainerActiveItemChange: function(container, value, oldValue, eOpts) {
        /* TODO
        if (value && value.Titolo) {
            var titoloSezioneLabel = Ext.ComponentQuery.query('#titoloSezioneTopBarLabel')[0];
            titoloSezioneLabel.setHtml(value.Titolo);
        }
        */
    },

    onEsciTopBarButtonTap: function(button, e, eOpts) {
        Ext.Msg.confirm('Uscita', 'Desideri uscire dalla sessione di lavoro?',
                        function (buttonId, value, opt) {
                            if (buttonId === 'yes') {
                                window.location = Infocar.app.loginPageUrl;
                            }
                        }
        );
    },

    launch: function() {
        /* Spostati nel launch dell'application
        Infocar.app.localize();

        Ext.defer(Infocar.app.checkSession, 2 * 60 * 1000, this);

        // Carico da back-end le informazioni relative all'utente
        Infocar.app.loadUtente();

        // Controllo l'orientamento del device in uso dall'utente e
        // riadatto la disposizione dei componenti.
        Infocar.app.checkOrientation();
        */
    }

});