/*
 * File: app/view/MainMenuLeft.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.MainMenuLeft', {
    extend: 'Ext.Menu',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        maxWidth: '36%',
        items: [
            {
                xtype: 'container',
                cls: 'titoloMenuLeftContainerCls',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        baseCls: 'titoloMenuLeftLabelCls',
                        html: 'MENU'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        height: 40,
                        itemId: 'hideMainMenuLeftButton',
                        iconCls: 'more'
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'HomeMenuLeftButtonCls',
                itemId: 'homeMenuLeftButton',
                iconCls: 'home',
                text: 'Home'
            },
            {
                xtype: 'button',
                cls: 'MenuLeftButtonCls',
                itemId: 'ricercaUsatoMenuLeftButton',
                iconCls: 'action',
                text: 'Preliminare ritiro usato'
            },
            {
                xtype: 'button',
                cls: 'MenuLeftButtonCls',
                itemId: 'ricercaNuovoMenuLeftButton',
                iconCls: 'action',
                text: 'Preliminare configuratore nuovo'
            },
            {
                xtype: 'button',
                cls: 'MenuLeftButtonCls',
                itemId: 'ricercaStockMenuLeftButton',
                iconCls: 'action',
                text: 'Ricerca stock'
            }
        ]
    }

});