/*
 * File: app/view/NuovoView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.NuovoView', {
    extend: 'Ext.Container',
    alias: 'widget.NuovoView',

    requires: [
        'Infocar.view.TopBar',
        'Ext.form.Panel',
        'Ext.field.Select',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Hidden',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.Img',
        'Ext.SegmentedButton',
        'Ext.dataview.List',
        'Ext.Toolbar',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    config: {
        itemId: 'nuovoView',
        items: [
            {
                xtype: 'TopBar'
            },
            {
                xtype: 'container',
                height: '100%',
                itemId: 'bodyNuovoContainer',
                layout: {
                    type: 'card',
                    animation: 'slide'
                },
                items: [
                    {
                        xtype: 'container',
                        Titolo: 'Configurazione - Ricerca nuovo',
                        itemId: 'ricercaNuovoContainer',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                ricercaTargaFlag: 'N',
                                height: 180,
                                itemId: 'ricercaNuovoForm',
                                layout: 'vbox',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        itemId: 'descrizioneRicercaNuovoField',
                                        label: 'Descrizione',
                                        labelWidth: 200,
                                        name: 'descrizione'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        label: 'Listino per',
                                        labelWidth: 200,
                                        name: 'listino_codice',
                                        autoSelect: false,
                                        displayField: 'descrizione',
                                        store: 'ListinoStore',
                                        valueField: 'codice'
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                flex: 1,
                                                label: 'Alimentazione',
                                                labelWidth: 200,
                                                name: 'alimentazione_codice',
                                                autoSelect: false,
                                                displayField: 'descrizione',
                                                store: 'AlimentazioneRicercaNuovoStore',
                                                valueField: 'codice'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 40
                                            },
                                            {
                                                xtype: 'selectfield',
                                                flex: 1,
                                                label: 'Carrozzeria',
                                                labelWidth: 200,
                                                name: 'carrozzeria_codice',
                                                autoSelect: false,
                                                displayField: 'descrizione',
                                                store: 'CarrozzeriaRicercaNuovoStore',
                                                valueField: 'codice'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'spacer',
                                                width: 200
                                            },
                                            {
                                                xtype: 'button',
                                                itemId: 'cercaRicNuovoButton',
                                                width: 140,
                                                text: 'Cerca'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 100
                                            },
                                            {
                                                xtype: 'button',
                                                itemId: 'azzeraRicNuovoButton',
                                                text: 'Azzera ricerca'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        itemId: 'marcaRicercaNuovoHidden',
                                        name: 'marca_codice'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        itemId: 'modelloRicercaNuovoHidden',
                                        name: 'modello_codice'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        itemId: 'allestimentoRicercaNuovoHidden',
                                        name: 'allestimento_codice'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'ricercaNuovoRisultatoContainer',
                                layout: {
                                    type: 'card',
                                    animation: 'slide'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'marcaRicNuovoRisultatoContainer',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'start'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'spacer',
                                                        width: 200
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        height: 40,
                                                        itemId: 'marcaRicNuovoNumRisultatiLabel'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                itemId: 'marcaRicNuovoRisultatoDataView',
                                                itemTpl: [
                                                    '<table class="marcaRicNuovoRisultatoDataViewTableCls">',
                                                    '  <tr>',
                                                    '    <td class="logoMarcaRicNuovoRisultatoDataViewTdCls"><img src="{urlImg}"></td>',
                                                    '    <td class="descrizioneMarcaRicNuovoRisultatoDataViewTdCls">{descrizione}</td>',
                                                    '    <td class="frecciaMarcaRicNuovoRisultatoDataViewTdCls"><img src="resources/images/freccia_dx.jpg"></td>',
                                                    '  </tr>',
                                                    '</table>',
                                                    ''
                                                ],
                                                store: 'MarcaRicercaNuovoStore'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        itemId: 'modelloRicNuovoRisultatoContainer',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'start'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'indietroModelloRicNuovoButton',
                                                        width: 100,
                                                        text: 'Indietro'
                                                    },
                                                    {
                                                        xtype: 'spacer',
                                                        width: 100
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        itemId: 'modelloRicNuovoNumRisultatiLabel'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                itemId: 'modelloRicNuovoRisultatoDataView',
                                                itemTpl: [
                                                    '<table class="modelloRicNuovoRisultatoDataViewTableCls">',
                                                    '  <tr>',
                                                    '    <td class="descrizioneModelloRicNuovoRisultatoDataViewTdCls">{descrizione}</td>',
                                                    '    <td class="frecciaModelloRicNuovoRisultatoDataViewTdCls"><img src="resources/images/freccia_dx.jpg"></td>',
                                                    '  </tr>',
                                                    '</table>',
                                                    ''
                                                ],
                                                store: 'ModelloRicercaNuovoStore',
                                                useComponents: false
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        itemId: 'allestimentoRicNuovoRisultatoContainer',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'start'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'indietroAllestimentoRicNuovoButton',
                                                        width: 100,
                                                        text: 'Indietro'
                                                    },
                                                    {
                                                        xtype: 'spacer',
                                                        width: 100
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        itemId: 'allestimentoRicNuovoNumRisultatiLabel'
                                                    },
                                                    {
                                                        xtype: 'spacer',
                                                        width: 100
                                                    },
                                                    {
                                                        xtype: 'selectfield',
                                                        itemId: 'ordinamentoRicNuovoComboBox',
                                                        label: 'Ordina per:',
                                                        labelWidth: '50%',
                                                        name: 'ordinamento_codice',
                                                        autoSelect: false,
                                                        displayField: 'descrizione',
                                                        store: 'OrdinamentoRicercaNuovoStore',
                                                        valueField: 'codice'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                itemId: 'allestimentoRicNuovoRisultatoDataView',
                                                itemTpl: [
                                                    '<table class="allestimentoRicNuovoRisultatoDataViewTableCls">',
                                                    '  <tr>',
                                                    '    <td class="descrizioneAllestimentoRicNuovoRisultatoDataViewTdCls">{descrizione}</td>',
                                                    '    <td class="frecciaAllestimentoRicNuovoRisultatoDataViewTdCls"><img src="resources/images/freccia_dx.jpg"></td>',
                                                    '  </tr>',
                                                    '</table>',
                                                    ''
                                                ],
                                                store: 'AllestimentoRicercaNuovoStore',
                                                useComponents: false
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        Titolo: 'Configurazione - Preliminare',
                        itemId: 'dettaglioVeicoloNuovoContainer',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                hidden: true,
                                itemId: 'testataDettVeicoloNuovoContainerLandscape',
                                layout: {
                                    type: 'vbox',
                                    align: 'start'
                                },
                                items: [
                                    {
                                        xtype: 'image',
                                        itemId: 'dettaglioVeicoloNuovoImg',
                                        width: '100%',
                                        mode: 'image'
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'descDettVeicoloNuovoLabel',
                                        tpl: [
                                            '{allestimento_descrizione}'
                                        ]
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'infoVeicoloNuovoButton',
                                        iconCls: 'info'
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'prezzoBaseDettVeicoloNuovoLabel',
                                        tpl: Ext.create('Ext.XTemplate', 
                                            'prezzo base: {veicoloBasePrezzo:this.fmtCurrency} &euro;',
                                            {
                                                fmtCurrency: function(currValue) {
                                                    return Infocar.app.formatCurrency(currValue);
                                                }
                                            }
                                        )
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'totaleDettVeicoloNuovoLabel',
                                        tpl: Ext.create('Ext.XTemplate', 
                                            '{totalePrezzo:this.fmtCurrency} &euro;',
                                            {
                                                fmtCurrency: function(currValue) {
                                                    return Infocar.app.formatCurrency(currValue);
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'testataDettVeicoloNuovoContainerPortrait',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                width: '16%',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        itemId: 'dettaglioVeicoloNuovoImg',
                                                        width: '100%',
                                                        mode: 'image'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                layout: 'vbox',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                itemId: 'descDettVeicoloNuovoLabel',
                                                                tpl: [
                                                                    '{allestimento_descrizione}'
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                itemId: 'infoVeicoloNuovoButton',
                                                                iconCls: 'info'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        itemId: 'prezzoBaseDettVeicoloNuovoLabel',
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            'prezzo base: {veicoloBasePrezzo:this.fmtCurrency} &euro;',
                                                            {
                                                                fmtCurrency: function(currValue) {
                                                                    return Infocar.app.formatCurrency(currValue);
                                                                }
                                                            }
                                                        )
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'label',
                                                docked: 'right',
                                                itemId: 'totaleDettVeicoloNuovoLabel',
                                                tpl: Ext.create('Ext.XTemplate', 
                                                    '{totalePrezzo:this.fmtCurrency} &euro;',
                                                    {
                                                        fmtCurrency: function(currValue) {
                                                            return Infocar.app.formatCurrency(currValue);
                                                        }
                                                    }
                                                )
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'segmentedbutton',
                                        itemId: 'clustersDettVeicoloNuovoButtons',
                                        items: [
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'tipoVeicoloClusterDettVeicoloNuovoButton',
                                                text: 'Tipo veicolo'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'esterniClusterDettVeicoloNuovoButton',
                                                text: 'Esterni'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'interniClusterDettVeicoloNuovoButton',
                                                text: 'Interni'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'sicurezzaClusterDettVeicoloNuovoButton',
                                                text: 'Sicurezza'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'comfortClusterDettVeicoloNuovoButton',
                                                text: 'Comfort'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'serviziClusterDettVeicoloNuovoButton',
                                                text: 'Servizi'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'tuttiClusterDettVeicoloNuovoButton',
                                                text: 'Tutti'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'pacchettiClusterDettVeicoloNuovoButton',
                                                text: 'Pacchetti'
                                            },
                                            {
                                                xtype: 'button',
                                                clusterCodice: null,
                                                flex: 1,
                                                height: 50,
                                                itemId: 'riepilogoClusterDettVeicoloNuovoButton',
                                                text: 'Riepilogo'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                flex: 1,
                                                itemId: 'cercaDettVeicoloNuovoTextbox',
                                                label: 'Cerca'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                flex: 1,
                                                itemId: 'logicaDettVeicoloNuovoCombobox',
                                                label: 'Logica',
                                                name: 'logica_codice',
                                                autoSelect: false,
                                                displayField: 'descrizione',
                                                store: 'LogicaStore',
                                                valueField: 'codice'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                margin: '0 10 0 10',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        width: '10%',
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                itemId: 'legendaHeaderEquipDettVeicoloNuovoButton',
                                                                width: 40,
                                                                text: '?'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        html: 'Descrizione',
                                                        itemId: 'descrizioneHeaderEquipDettVeicoloNuovoButton',
                                                        width: '75%'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        html: 'Prezzo &euro;',
                                                        itemId: 'prezzoHeaderEquipDettVeicoloNuovoButton',
                                                        width: '15%'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                flex: 1,
                                                itemId: 'equipDettVeicoloNuovoList',
                                                disableSelection: true,
                                                defaultType: 'EquipDettVeicoloNuovoListItem',
                                                scrollToTopOnRefresh: false,
                                                store: 'EquipDettVeicoloNuovoStore',
                                                grouped: true,
                                                useSimpleItems: false
                                            },
                                            {
                                                xtype: 'panel',
                                                centered: true,
                                                height: 400,
                                                hidden: true,
                                                itemId: 'popupInformEquipDettVeicoloNuovoPanel',
                                                width: 600,
                                                hideOnMaskTap: true,
                                                layout: 'vbox',
                                                modal: true,
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        height: 50,
                                                        itemId: 'titleBarInformEquipDettVeicoloNuovoContainer',
                                                        width: '100%',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'container',
                                                                flex: 1,
                                                                html: 'Info',
                                                                itemId: 'titoloInformEquipDettVeicoloNuovoLabel'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                docked: 'right',
                                                                itemId: 'closeInformEquipDettVeicoloNuovoButton',
                                                                iconCls: 'star'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        height: 320,
                                                        itemId: 'testoInformEquipDettVeicoloNuovoContainer',
                                                        margin: 10,
                                                        tpl: Ext.create('Ext.XTemplate', 
                                                            '<tpl if="typeof this.livello !=\'undefined\'">',
                                                            '  {% ++this.livello; %}',
                                                            '<tpl else>',
                                                            '  {% this.livello=1; %}',
                                                            '  <table style="width: 100%; background-color: #cccccc;">',
                                                            '    <tr>',
                                                            '      <td style="width: 20%; text-align: center; padding: 5px 10px;">E I V</td>',
                                                            '      <td style="width: 80%; text-align: left; padding: 5px 10px;">{[this.equipaggiamentoSelez]}</td>',
                                                            '    </tr>',
                                                            '  </table>',
                                                            '</tpl>',
                                                            '<tpl for="items">',
                                                            '    <tpl if="this.livello==1">',
                                                            '      <tpl if="items">',
                                                            '        <div style="background-color: #cccccc; margin: 10px 0px; padding: 5px 10px;">{descrizione}</div>',
                                                            '        {[this.recurse(values)]}',
                                                            '      <tpl else>',
                                                            '        <table style="width: 100%;">',
                                                            '          <tr>',
                                                            '            <td style="width: 20%; text-align: center; padding: 5px 10px;"><img src="{eivUrlImg}"></td>',
                                                            '            <td style="width: 80%; text-align: left; padding: 5px 10px;">{descrizione}</td>',
                                                            '          </tr>',
                                                            '        </table>',
                                                            '      </tpl>',
                                                            '    <tpl else>',
                                                            '      <div style="margin: 10px;">',
                                                            '        <span style="height: 20px;">- {descrizione}</span>',
                                                            '        <tpl if="items">',
                                                            '          {[this.recurse(values)]}',
                                                            '        </tpl>',
                                                            '      </div>',
                                                            '    </tpl>',
                                                            '</tpl>',
                                                            '{% if (!this.livello || --this.livello < 1) delete this.livello; %}',
                                                            '',
                                                            {
                                                                recurse: function(values) {
                                                                    return this.apply(values);
                                                                }
                                                            }
                                                        ),
                                                        scrollable: 'vertical'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'panel',
                                                height: 220,
                                                hidden: true,
                                                itemId: 'popupLegendaEquipDettVeicoloNuovoPanel',
                                                width: 320,
                                                hideOnMaskTap: true,
                                                modal: true,
                                                layout: {
                                                    type: 'vbox',
                                                    align: 'start'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        width: '100%',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                docked: 'right',
                                                                itemId: 'closeLegendaEquipDettVeicoloNuovoButton',
                                                                iconCls: 'star'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        html: '<div style="font-weight: bold">Legenda:</div>  <div style="height: 10px"></div> <table class="testoLegendaEquipDettVeicoloNuovoTableStyle">   <tr>     <td><img src="resources/images/stato_libero.jpg" width="16" height="16"></td>     <td>Libero</td>   </tr>   <tr>     <td><img src="resources/images/stato_selez.png" width="16" height="16"></td>     <td>Selezionato</td>   </tr>   <tr>     <td><img src="resources/images/stato_incluso.jpg" width="16" height="16"></td>     <td style="font-weight: bold">Incluso</td>   </tr>   <tr>     <td><img src="resources/images/stato_non_disp.jpg" width="16" height="16"></td>     <td style="font-weight: bold">Non Disponibile</td>   </tr> </table>',
                                                        itemId: 'testoLegendaEquipDettVeicoloNuovoLabel',
                                                        margin: '0 0 0 20'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        height: 200,
                                        hidden: true,
                                        itemId: 'popupEquipSelAutomaticaDettVeicoloNuovoPanel',
                                        right: 10,
                                        top: 80,
                                        width: 300,
                                        hideOnMaskTap: false,
                                        layout: 'vbox',
                                        modal: false,
                                        items: [
                                            {
                                                xtype: 'container',
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        docked: 'right',
                                                        itemId: 'closeEquipSelAutomaticaDettVeicoloNuovoButton',
                                                        iconCls: 'star'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'label',
                                                height: 60,
                                                hidden: false,
                                                html: 'Selezionati in automatico gli equipaggiamenti:',
                                                itemId: 'msgEquipSelAutomaticaDettVeicoloNuovoLabel'
                                            },
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                itemId: 'equipSelAutomaticaDettVeicoloNuovoDataview',
                                                itemTpl: [
                                                    '<div>&nbsp;- {descrizione}</div>'
                                                ],
                                                store: 'EquipSelAutomaticaDettVeicoloNuovoStore'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        centered: true,
                                        height: 400,
                                        hidden: true,
                                        itemId: 'popupEquipDettVeicoloNuovoPanel',
                                        width: 600,
                                        hideOnMaskTap: false,
                                        modal: true,
                                        layout: {
                                            type: 'vbox',
                                            align: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'label',
                                                itemId: 'titoloPopupEquipVeicoloNuovoLabel',
                                                tpl: [
                                                    'Selezionare uno dei seguenti equipaggiamenti da associare a {descEquipSelezionato} ',
                                                    '(dove {descEquipSelezionato} &egrave; il vincolante)'
                                                ]
                                            },
                                            {
                                                xtype: 'dataview',
                                                height: 300,
                                                hidden: false,
                                                itemId: 'popupEquipDettVeicoloNuovoDataView',
                                                width: 500,
                                                itemTpl: [
                                                    '<table class="popupEquipDettVeicoloNuovoDataViewTableCls">',
                                                    '  <tr>',
                                                    '    <td class="chkboxPopupEquipDettVeicoloNuovoDataViewTdCls"></td>',
                                                    '    <td class="descrizionePopupEquipDettVeicoloNuovoDataViewTdCls">{descrizione}</td>',
                                                    '    <td class="prezzoPopupEquipDettVeicoloNuovoDataViewTdCls">{equipPrezzo}</td>',
                                                    '  </tr>',
                                                    '</table>',
                                                    ''
                                                ],
                                                selectedCls: 'selezionePopupEquipDettVeicoloNuovoDataViewSelectedCls',
                                                store: 'PopupEquipDettVeicoloNuovoStore',
                                                useComponents: false
                                            },
                                            {
                                                xtype: 'container',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'annullaPopupEquipVeicoloNuovoButton',
                                                        text: 'Annulla tutto'
                                                    },
                                                    {
                                                        xtype: 'spacer',
                                                        width: 100
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'confermaPopupEquipVeicoloNuovoButton',
                                                        text: 'Scegli'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                hidden: false,
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'indietroDettaglioVeicoloNuovoButton',
                                        text: 'Indietro'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'stampaEsitoVeicoloNuovoButton',
                                        text: 'Stampa'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        itemId: 'salvaDettaglioVeicoloNuovoButton',
                                        text: 'Salva'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        Titolo: 'Configurazione - Dettaglio del modello',
                        itemId: 'infoVeicoloNuovoContainer',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                hidden: true,
                                itemId: 'testataInfoVeicoloNuovoContainerLandscape',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'image',
                                        itemId: 'infoVeicoloNuovoMiniImg',
                                        width: '100%',
                                        mode: 'image'
                                    },
                                    {
                                        xtype: 'label',
                                        itemId: 'descInfoVeicoloNuovoLabel',
                                        tpl: [
                                            '{allestimento_descrizione}'
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'testataInfoVeicoloNuovoContainerPortrait',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        itemId: 'infoVeicoloNuovoMiniImg',
                                                        width: '100%',
                                                        mode: 'image'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'label',
                                                itemId: 'descInfoVeicoloNuovoLabel',
                                                tpl: [
                                                    '{allestimento_descrizione}'
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        itemId: 'corpoInfoVeicoloNuovoContainer',
                                        layout: {
                                            type: 'card',
                                            animation: 'slide'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                itemId: 'generaleInfoVeicoloNuovoContainer',
                                                layout: 'vbox',
                                                scrollable: 'vertical',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'container',
                                                                width: '50%',
                                                                items: [
                                                                    {
                                                                        xtype: 'image',
                                                                        itemId: 'infoVeicoloNuovoImg',
                                                                        width: '100%',
                                                                        mode: 'image'
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                itemId: 'testoInfoVeicoloNuovoLabel',
                                                                tpl: Ext.create('Ext.XTemplate', 
                                                                    '<table border="0">',
                                                                    '    <tr>',
                                                                    '        <td>Data listino:</td>',
                                                                    '        <td align="right">{dataListino:date(\'d/m/Y\')}</td>',
                                                                    '    </tr>',
                                                                    '    <tr>',
                                                                    '        <td>Prezzo listino:</td>',
                                                                    '        <td align="right">{listinoPrezzo:this.fmtCurrency} &euro;</td>',
                                                                    '    </tr>',
                                                                    '    <tr>',
                                                                    '        <td>Prezzo chiavi in mano:</td>',
                                                                    '        <td align="right">{cmPrezzo:this.fmtCurrency} &euro;</td>',
                                                                    '    </tr>',
                                                                    '</table>',
                                                                    '<br>',
                                                                    '<div class="">',
                                                                    'Codice infocar: {codiceInfocar}<br>',
                                                                    'Codice casa: {codiceCasa}<br>',
                                                                    'Codice QUD: {codiceQUD}<br>',
                                                                    'Omologazioni: {omologazioni}<br>',
                                                                    '</div>',
                                                                    {
                                                                        fmtCurrency: function(currValue) {
                                                                            return Infocar.app.formatCurrency(currValue);
                                                                        }
                                                                    }
                                                                ),
                                                                width: '50%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        itemId: 'sintesiDatiTecniciInfoVeicoloNuovoContainer',
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'start'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                itemId: 'sintesiDatiTecniciInfoVeicoloNuovoLabel',
                                                                tpl: [
                                                                    '<div class="">Dati tecnici</div>',
                                                                    '<br>',
                                                                    '<div class="">',
                                                                    'Alimentazione: {alimentazione_descrizione}&nbsp;&nbsp;',
                                                                    'Cilindrata cm<sup>3</sup>: {cilindrata}&nbsp;&nbsp;',
                                                                    'Potenza kW/CV: {potenza}<br>',
                                                                    'Carrozzeria: {carrozzeria_descrizione}&nbsp;&nbsp;',
                                                                    'Normativa: {normativa}',
                                                                    '</div>'
                                                                ],
                                                                width: '80%'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                hidden: false,
                                                                itemId: 'datiTecniciInfoVeicoloNuovoButton',
                                                                width: '20%',
                                                                text: 'Scopri tutti i dati tecnici'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        itemId: 'sintesiEquipInfoVeicoloNuovoContainer',
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'start'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                itemId: 'sintesiEquipInfoVeicoloNuovoLabel',
                                                                tpl: [
                                                                    '<div class="">Equipaggiamenti</div>',
                                                                    '<br>',
                                                                    '<div class="">',
                                                                    'Questo allestimento comprende {numEquip} equipaggiamenti',
                                                                    '</div>'
                                                                ],
                                                                width: '80%'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                hidden: false,
                                                                itemId: 'equipInfoVeicoloNuovoButton',
                                                                width: '20%',
                                                                text: 'Scopri tutti gli equipaggiamenti'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        itemId: 'sintesiSituazioneStockVeicoloNuovoContainer',
                                                        layout: 'hbox',
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                html: 'Valori previsivi non disponibili',
                                                                itemId: 'messaggioGraficoInfoVeicoloNuovoLabel',
                                                                width: '50%'
                                                            },
                                                            {
                                                                xtype: 'chart',
                                                                height: 300,
                                                                hidden: true,
                                                                itemId: 'graficoInfoVeicoloNuovoChart',
                                                                width: '50%',
                                                                colors: [
                                                                    '#115fa6',
                                                                    '#94ae0a',
                                                                    '#a61120',
                                                                    '#ff8809',
                                                                    '#ffd13e',
                                                                    '#a61187',
                                                                    '#24ad9a',
                                                                    '#7c7474',
                                                                    '#a66111'
                                                                ],
                                                                store: 'GraficoInfoVeicoloNuovoStore',
                                                                axes: [
                                                                    {
                                                                        type: 'category',
                                                                        fields: [
                                                                            'valoreX'
                                                                        ]
                                                                    },
                                                                    {
                                                                        type: 'numeric',
                                                                        fields: [
                                                                            'valoreY1',
                                                                            'valoreY2'
                                                                        ],
                                                                        grid: {
                                                                            odd: {
                                                                                fill: '#e8e8e8'
                                                                            }
                                                                        },
                                                                        position: 'left'
                                                                    }
                                                                ],
                                                                series: [
                                                                    {
                                                                        type: 'line',
                                                                        colors: 'rgba(0,200,0,0.3)',
                                                                        marker: {
                                                                            type: 'circle',
                                                                            fill: 'rgb(0,200,0)',
                                                                            radius: 4
                                                                        },
                                                                        style: {
                                                                            stroke: 'rgb(0,200,0)',
                                                                            lineWidth: 2
                                                                        },
                                                                        xField: 'valoreX',
                                                                        yField: 'valoreY1'
                                                                    },
                                                                    {
                                                                        type: 'line',
                                                                        colors: 'transparent',
                                                                        marker: {
                                                                            type: 'circle',
                                                                            fill: 'rgb(0,0,200)',
                                                                            radius: 4
                                                                        },
                                                                        style: {
                                                                            stroke: 'rgb(0,0,200)',
                                                                            lineWidth: 2
                                                                        },
                                                                        xField: 'valoreX',
                                                                        yField: 'valoreY2'
                                                                    }
                                                                ],
                                                                interactions: [
                                                                    {
                                                                        type: 'panzoom'
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                itemId: 'sintesiDatiStockInfoVeicoloNuovoLabel',
                                                                tpl: Ext.create('Ext.XTemplate', 
                                                                    '<table border="0" cellspacing="4" cellpadding="4">',
                                                                    '    <tr>',
                                                                    '        <td align="left">In stock</td>',
                                                                    '        <td>Fisico</td>',
                                                                    '        <td>Virtuale</td>',
                                                                    '        <td>Giacenza</td>',
                                                                    '        <td>Giacenza media</td>',
                                                                    '    </tr>',
                                                                    '    <tr>',
                                                                    '        <td align="left">Allestimento</td>',
                                                                    '        <td>{allestimentoFisicoStock:this.fmtInt}</td>',
                                                                    '        <td>{allestimentoVirtualeStock:this.fmtInt}</td>',
                                                                    '        <td>{allestimentoGiacenzaStock:this.fmtInt}</td>',
                                                                    '        <td>{allestimentoGiacMediaStock:this.fmtInt}&nbsp;<img src="{allestimentoGiacenzaStockUrlImg}"></td>',
                                                                    '    </tr>',
                                                                    '    <tr>',
                                                                    '        <td align="left">Modello</td>',
                                                                    '        <td>{modelloFisicoStock:this.fmtInt}</td>',
                                                                    '        <td>{modelloVirtualeStock:this.fmtInt}</td>',
                                                                    '        <td>{modelloGiacenzaStock:this.fmtInt}</td>',
                                                                    '        <td>{modelloGiacMediaStock:this.fmtInt}&nbsp;<img src="{modelloGiacenzaStockUrlImg}"></td>',
                                                                    '    </tr>',
                                                                    '</table>',
                                                                    {
                                                                        fmtInt: function(intValue) {
                                                                            return Infocar.app.formatInt(intValue);
                                                                        }
                                                                    }
                                                                ),
                                                                width: '50%'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'datiTecniciInfoVeicoloNuovoContainer',
                                                layout: 'vbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        html: 'Dati tecnici'
                                                    },
                                                    {
                                                        xtype: 'list',
                                                        flex: 1,
                                                        disableSelection: true,
                                                        itemTpl: [
                                                            '<table border="0">',
                                                            '  <tr>',
                                                            '    <td style="width: 200px">{nomeAttributo}:</td>',
                                                            '    <td>{valoreAttributo}</td>',
                                                            '  </tr>',
                                                            '</table>'
                                                        ],
                                                        store: 'DatiTecniciInfoVeicoloNuovoStore',
                                                        grouped: true
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                itemId: 'equipInfoVeicoloNuovoContainer',
                                                layout: 'vbox',
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        html: 'Tutti gli equipaggiamenti'
                                                    },
                                                    {
                                                        xtype: 'dataview',
                                                        flex: 1,
                                                        itemTpl: Ext.create('Ext.XTemplate', 
                                                            '<div> - {descrizione}</div>',
                                                            {
                                                                disableFormats: true
                                                            }
                                                        ),
                                                        store: 'EquipInfoVeicoloNuovoStore'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                hidden: false,
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'indietroInfoVeicoloNuovoButton',
                                        text: 'Indietro'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        Titolo: 'Configurazione - Esito',
                        itemId: 'esitoVeicoloNuovoContainer',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'label',
                                itemId: 'testoEsitoVeicoloNuovoLabel',
                                tpl: [
                                    '<div style="height:100px"></div>',
                                    '',
                                    '<p>Preliminare di vendita</p>',
                                    '<p>l\'operazione &egrave; stata salvata correttamente, per poterla modificare ',
                                    'sar&agrave; necessario accedere al sito InfocarWeb 3.0 da un personal computer.</p>',
                                    '',
                                    '<div style="height:100px"></div>',
                                    '',
                                    '<p>Riepilogo</p>',
                                    '',
                                    '<br>',
                                    '',
                                    '{allestimento_descrizione}'
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 120,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Prezzo chiavi in mano',
                                                width: '25%'
                                            },
                                            {
                                                xtype: 'label',
                                                itemId: 'veicoloBasePrezzoEsitoVeicoloNuovoLabel2',
                                                tpl: Ext.create('Ext.XTemplate', 
                                                    '{veicoloBasePrezzo:this.fmtCurrency} &euro;',
                                                    {
                                                        fmtCurrency: function(currValue) {
                                                            return Infocar.app.formatCurrency(currValue);
                                                        }
                                                    }
                                                ),
                                                width: '25%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Equipaggiamenti selezionati',
                                                width: '25%'
                                            },
                                            {
                                                xtype: 'label',
                                                itemId: 'equipaggiamentiPrezzoEsitoVeicoloNuovoLabel2',
                                                tpl: Ext.create('Ext.XTemplate', 
                                                    '{equipaggiamentiPrezzo:this.fmtCurrency} &euro;',
                                                    {
                                                        fmtCurrency: function(currValue) {
                                                            return Infocar.app.formatCurrency(currValue);
                                                        }
                                                    }
                                                ),
                                                width: '25%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Totale Veicolo',
                                                width: '25%'
                                            },
                                            {
                                                xtype: 'label',
                                                itemId: 'totalePrezzoEsitoVeicoloNuovoLabel2',
                                                tpl: Ext.create('Ext.XTemplate', 
                                                    '{totalePrezzo:this.fmtCurrency} &euro;',
                                                    {
                                                        fmtCurrency: function(currValue) {
                                                            return Infocar.app.formatCurrency(currValue);
                                                        }
                                                    }
                                                ),
                                                width: '25%'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'stampaEsitoVeicoloNuovoButton',
                                        text: 'Stampa'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        itemId: 'ricercaUsatoEsitoVeicoloNuovoButton',
                                        text: 'Ritiro usato'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        itemId: 'ricercaStockEsitoVeicoloNuovoButton',
                                        text: 'Lista stock'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});