/*
 * File: app/view/TopBar.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.view.TopBar', {
    extend: 'Ext.Container',
    alias: 'widget.TopBar',

    requires: [
        'Ext.Button',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.Img'
    ],

    config: {
        docked: 'top',
        height: 40,
        itemId: 'topBar',
        layout: {
            type: 'hbox',
            align: 'start'
        },
        items: [
            {
                xtype: 'button',
                itemId: 'showMainMenuLeftButton',
                iconCls: 'more'
            },
            {
                xtype: 'label',
                itemId: 'titoloSezioneTopBarLabel',
                width: 350
            },
            {
                xtype: 'button',
                docked: 'right',
                itemId: 'esciTopBarButton',
                text: 'Esci'
            },
            {
                xtype: 'label',
                docked: 'right',
                itemId: 'userNameTopBarLabel',
                tpl: [
                    '{nomeUtente} {cognomeUtente}'
                ],
                width: 200
            },
            {
                xtype: 'image',
                docked: 'right',
                width: 60
            }
        ]
    }

});