/*
 * File: app/store/ModelloRicercaUsatoStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Infocar.store.ModelloRicercaUsatoStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Infocar.model.ModelloModel',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    config: {
        data: [
            {
                codice: 1,
                descrizione: 'modello 1'
            },
            {
                codice: 2,
                descrizione: 'modello 2'
            },
            {
                codice: 3,
                descrizione: 'modello 3'
            },
            {
                codice: 4,
                descrizione: 'modello 4'
            }
        ],
        model: 'Infocar.model.ModelloModel',
        storeId: 'ModelloRicercaUsatoStore',
        proxy: {
            type: 'rest',
            url: '/usato/modello',
            appendId: false,
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});